version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: ecommerce-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: always
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecommerce
      - JWT_SECRET=supersecretkey
      - PORT=4000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
